from setuptools import setup, find_packages

setup(
    name='find_hotels',
    version='1.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
    'beautifulsoup4==4.7.1',
    'branca==0.3.1',
    'certifi==2018.11.29',
    'chardet==3.0.4',
    'Click==7.0',
    'colorama==0.4.1',
    'configparser==3.7.4',
    'crayons==0.2.0',
    'Flask==1.0.2',
    'folium==0.8.2',
    'geographiclib==1.49',
    'geoid==1.1.0',
    'geopy==1.18.1',
    'idna==2.8',
    'itsdangerous==1.1.0',
    'Jinja2==2.10',
    'MarkupSafe==1.1.1',
    'numpy==1.22.0',
    'requests==2.21.0',
    'selenium==3.141.0',
    'six==1.12.0',
    'soupsieve==1.8',
    'urllib3==1.24.1',
    'webdriver-manager==1.7',
    'Werkzeug==0.15.2',
    'zomatopy==1.0.10'],
    url='',
    license='',
    author='Olena Matrunych',
    author_email='matrunych@ucu.edu.ua',
    description='Help to find cheap hotels with restaurants nearby'
)
